[project]
name = "strands-handson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.12",
    "python-dotenv>=1.2.1",
    "strands-agents>=1.21.0",
    "streamlit==1.49.1",
]
